[project]
name = "comm4190-f25-using-llms-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.1",
    "openai>=1.54.0",
    "python-dotenv>=1.0.1",
]
